name: Run Turnout Comparison

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib

    - name: Change directory to scripts and run script
      run: |
        cd 2024-07-06_bakap
        python script.py  # Ensure the path to the script is correct

    - name: List files after script execution
      run: ls -la

    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add turnout.png alt_text.txt
        git commit -m "Update plot and ALT text" || exit 0
        git push
